config:
  # this tells the NATS server to use the K8s service for the client connection
  client_advertise: "nats://nats-east.default.svc.cluster.local:4222"
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
  leafnodes:
    enabled: true
  gateway: 
    # NOTE: the gateway name must match the Helm release name
    # so if you run `helm install nats-east ...` the gateway name must be `nats-east`
    name: "nats-east"
    enabled: true
    # merge:
    #   advertise: "<your-load-balancer-endpoint>:7222"
    #   authorization:
    #     user: natsgate
    #     password: NATSC!u5t3rGa73way
      # for this demo, I used the cloud provider's load balancer servicer.
      # that means I had to wait for the load balancer to be created before I knew
      # what the external IP address was. until then, the following two lines were
      # commented out. once the load balancer was created, I uncommented them
      # and updated the values entries with the correct endpoints.
      # gateways: 
      # - name: "nats-east"
      #   urls:
      #     - nats://natsgate:NATSC!u5t3rGa73way@<your-load-balancer-endpoint>:7222
      # - name: "nats-west"
      #   urls:
      #     - nats://natsgate:NATSC!u5t3rGa73way@<your-load-balancer-endpoint>:7222
  merge:
    accounts:
      SYS:
        users:
          - user: sys
            pass: sysuser
      # primary account that was used to deploy the services in this demo
      teamA:
        jetstream: enabled
        users:
          # the four math operator services used this user
          - user: nats_operators
            pass: NATS0per@tors
            permissions:
              publish:
                allow: "$SRV.>"
              subscribe:
                allow: 
                - "$SRV.>" # necessary for service metrics
                - "math.numbers.>"
                - "_INBOX.>" # necessary for responses
              allow_responses: true
          # the requester job used this user
          - user: nats_requesters
            pass: NATSR3qu3st3rs
            permissions:
              publish:
                allow: "math.numbers.>"
              subscribe:
                allow: 
                - "_INBOX.>" # necessary for responses
      # Another account, if we want to see how cross-account traffic is restricted
      teamB:
        users:
          - user: natsUserB
            pass: NATS_U$3R_b33
    system_account: SYS

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

# this block configures the K8s service to use the AWS load balancer
service:
  ports:
    gateway:
      enabled: true
  merge:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    spec:
      type: LoadBalancer
      publishNotReadyAddresses: true
      ports:
        - name: nats
          port: 4222
          targetPort: 4222
        - name: gateway
          port: 7222
          targetPort: 7222


