apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder-deployment
  labels:
    app: adder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adder
  template:
    metadata:
      labels:
        app: adder
    spec:
      containers:
        - name: adder
          image: ghcr.io/synadia-labs/nats-cluster-demo-adder:latest
          imagePullPolicy: Always
          env:
            - name: NATS_USER
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: operator-username
            - name: NATS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: operator-password
            - name: NATS_SERVERS
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: nats-servers
            - name: REGION 
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: region
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "250m"